### ISSUE TITLE
logo/icon request 

### ISSUE THREAD

**Issue by hafizahmmed** [oliviertavel/PrivateAppStore#2]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![privateappstore-01](https://user-images.githubusercontent.com/38810169/39400259-eea0f876-4b4e-11e8-930d-b50f4e9549c4.jpg)

Thankyou

**Comment by oliviertavel** [comment]
Hi ! Thank you for your issue. However, we juste start the projet and we don't have fix the design guideline. We will reflect on your proposal.
